### PR TITLE
giveawaydrasil

### PR DESCRIPTION
**Pull request by SplitPixl**
please why can i not race car giveawaybot i want a refund

### CODE REVIEW

**Comment by Sanduhr32** [comment]
Indeed a no.

**Comment by Sanduhr32** [comment]
May the council @jagrosh decide your fate.

**Comment by SplitPixl** [comment]
i will ask jagrosh to merge next time i am in vrchat with him

**Comment by Sanduhr32** [comment]
Ok.

**Review by MichailiK — APPROVED** [review]
a

**Pull request closed without merging**
