### PR TITLE
just a bugfix nothing to see here

### PR DESCRIPTION
**Pull request by devsnek**

### CODE REVIEW

**Comment by datitisev** [comment]
LMAO 😂

I support this bug fix.

**Comment by TriggerRimfire** [comment]
I'm fairly sure that ID is incorrect, it should be `180731582049550336`. However, I think adding the above IDs to an array and picking a random one from that should make it a little more fair. Make sure that the only IDs that can be picked are from that array though and have a fallback in place in case the user is not in the server where the giveaway is being ran, that could be the global user pool for the bot. Most importantly though, the users in the special array should always be considered before anyone else.

**Comment by TheMonitorLizard** [comment]
Can we please stop raiding the repo? Thanks.

**Comment by nullpixel1** [comment]
@TheMonitorLizard What's raiding about this, and who are you to enforce this?

**Comment by TheMonitorLizard** [comment]
Not anyone to enforce. But let's be fair, this is a """"raid"""" in the sense you're circle-jerking a PR that is most certainly _not_ serious. As for my """"enforcing"""" I **asked** please and thank you because I regularly view this and other repo's from @jagrosh, and this is essentially providing empty notifications. I am not telling you guys to stop, I am asking nicely.

**Comment by nullpixel1** [comment]
Ah

**Pull request closed without merging**
