### PR TITLE
Added Gradle

### PR DESCRIPTION
**Pull request by Dunciboy**
- ~~Improved lambda expressions.~~
- ~~Reordered code.~~
- ~~Optimized imports.~~
- ~~Added warning suppressions.~~
- ~~Changed config to JSON.~~
- ~~Made prefix configurable.~~
- ~~Made owner id configurable.~~
- Added Gradle.

Just squash commit this if it's to your liking or if you want some changes to be made before that don't hesitate to ask.

### CODE REVIEW

**Comment by jagrosh** [comment]
My initial reaction to this PR is to not merge it:
1. Almost all the code within the java that you edited no longer exists; it has been rewritten locally and I plan to push once it is live on the bot
2. Making prefix and owner ID configurable, as well as adding gradle, do not seem to provide benefit, because:
    a) I don't build with gradle, nor would my owner ID nor my prefix change
    b) This bot does not support self-hosting, as I don't have the resources to provide help/support for it, and (in the rewritten state) needs several other specifically-set-up items
You are welcome to maintain your own branch of course; I just don't see the benefits of this merge for this repo

**Comment by Dunciboy** [comment]
Gradle is mainly beneficial for this project since like you said you don't plan on providing help and support on it, Gradle automatically downloads dependencies. Even if Gradle is set up in the project you don't need to use to build it you can still use your usual IDE to build but Gradle will be kind enough to import and download dependencies for you and changing dependency version is easy as enabling auto-import and changing a version number in the build.gradle.

I can see that the merge of the modified code might not be such a good idea since you did a rewrite. You should try and use GitHub to maintain your changes constantly though because:

- Backups.
- Possibility to revert.
- Friendlier to other forks (it's easier to merge a small commit then a large one).
- You can use another branch if you want to keep versions separated, until they are finished.

At the very least I would add Gradle to this project, if you wish to use Gradle i'll revert the code changes.

**Comment by TheMonitorLizard** [comment]
I don't think you get what jagrosh is saying:

Personally having worked with him, he prefers Maven, and has never been fond of Gradle. Any Gradle support is ultimately useless when taking that into consideration.

Not to mention you've virtually added nothing to the bot and seem to believe that this is some kinda selfhost similar to RedBot.

**The bot was not made for selfhosting**.

Even the offer jag had made to you about "maintaining your own fork" is just courtesy that the licensing would give you, provided you paid him 100% credit for the bot if you did manage to run it on your own.

As for "tweaks to the code" such as lambda improvement there has been absolutely no efficiency change at all, and actually more overhead introduced in place of a system that actually worked.

If you had made actual additions or useful modifications to the code, then there may have been some merit to a PR, but otherwise I personally fail to see really anything of worth.

**Comment by Dunciboy** [comment]
The main purpose of of this PR was not making the bot selfhostable, but merely making this repository more friendly to be used by other developers as there is no .gitignore or libraries included in this repository. It's not because allot of people keep asking how to set this bot up that sudenly everyone has the same intention.

This pull request is merely an attempt to make forking and using this source material more friendly towards other developers who might want to make it selfhostable or do something else with it. You need to set up a .gitignore and download all libraries manually.  If you don't want to do this and merely just want to share the code, then you are free to do so and close this PR.

I appreciate the fact you want to make the code open source even if you don't want to provide support for it.

That being said if you don't want to make these changes just close this PR, it's your repository @jagrosh I'm just putting in a suggestion for change, if you don't like it don't merge it.

**Comment by Dunciboy** [comment]
Since you added maven I presume this pull request won't be used so I'm closing it.

**Pull request closed without merging**
