### PR TITLE
Correctly pluralize in secondsToTime, fixes #14

### LINKED ISSUE #14: "Time remaining: 1 hours"
[https://i.imgur.com/RggnyjX.png](url)
This is a minor grammatical problem, but should also be a minor fix.

### PR DESCRIPTION
**Pull request by okx-code**

### CODE REVIEW

**Comment by jagrosh** [comment]
Similar to my comments on #15 (specifically https://github.com/jagrosh/GiveawayBot/pull/15#issuecomment-401449035), I'd like if all pluralization was fixed instead of just one instance of missing pluralization.

**Comment by okx-code** [comment]
@jagrosh I've fixed it since then but you haven't responded?

**Comment by jagrosh** [comment]
There are currently unresolved conflicts, so it can't be merged until you rebase your branch to master and fix the conflicts.

**Comment by okx-code** [comment]
Fixed @jagrosh

**Pull request merged**
